name: Release
on:
  release:
    types: [created]

jobs:
  release:
    name: Node.js Latest Full
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
          registry-url: https://npm.pkg.github.com/
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Release packages
        run: pnpm release
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}